version: "3.7"

volumes:
  postgres_data: { }
  storage_data: { }

services:
  #  UNCOMMENT postgres and redis SERVICES IF YOU ARE USING PROJECT IN LOCAL DEVELOPMENT or else comment it out

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  chatsupport:
    build:
      context: .

#    Uncomment command for use in production development
    # command: >
    #   sh -c "python manage.py migrate_schemas --shared"

#    used in local development with docker. Comment if using in production
#    command: >
#          sh -c "python manage.py migrate_schemas --shared &&
#                  python manage.py runserver 0.0.0.0:8000"

    volumes:
      - storage_data:/chatsupport/media
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_PORT=5432
    # expose:
    #   - 8000
    restart: always
    command: bash entrypoint.sh
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    volumes:
      - storage_data:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - chatsupport    

  channels:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 chatsupport.asgi:channel_layers
    env_file:
      - .env
    volumes:
      - .:/chatsupport
    ports:
      - "8001:8001"
    links:
      - redis

