# Generated by Django 3.2.5 on 2021-07-05 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tenant_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
