# Generated by Django 3.2.5 on 2022-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiverHasRead',
            field=models.BooleanField(default=False),
        ),
    ]
