# Generated by Django 3.2.5 on 2022-07-15 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='agents',
        ),
        migrations.AddField(
            model_name='room',
            name='agents',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='account.account'),
            preserve_default=False,
        ),
    ]
