# Generated by Django 3.2.5 on 2022-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_room_last_sent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='chat', max_length=10),
        ),
    ]
